from typing import List, Protocol


class SecondBrainRepository(Protocol):
    def save(self, file_path: str, content: str) -> None: ...

    def search(self, query: str, extension: str) -> List[str]: ...

    def get_all_notes(self, extension: str) -> List[str]: ...

    def read(self, file_path: str) -> str: ...

    def copy_asset(self, source_file: str, dest_path: str) -> str: ...
